### PR TITLE
Fix incorrect state after indicator cancellation

### LINKED ISSUE #213: Incorrect state after indicator cancellation
**Describe the bug**
Error and incorrect message after indicator cancellation.

**To Reproduce**
1. Generate tests
2. Click "cancel" button in the bottom during generation
3. See error

```
java.lang.IllegalStateException
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.throwInvalidState(AbstractProgressIndicatorBase.java:130)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.stop(AbstractProgressIndicatorBase.java:121)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.stop(AbstractProgressIndicatorExBase.java:52)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.delegate(AbstractProgressIndicatorExBase.java:211)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.doDelegateRunningChange(AbstractProgressIndicatorExBase.java:195)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.stop(AbstractProgressIndicatorExBase.java:53)
	at com.intellij.openapi.wm.impl.status.InfoAndProgressPanel$MyInlineProgressIndicator.stop(InfoAndProgressPanel.kt:830)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.delegate(AbstractProgressIndicatorExBase.java:211)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.doDelegateRunningChange(AbstractProgressIndicatorExBase.java:195)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.stop(AbstractProgressIndicatorExBase.java:53)
	at com.intellij.openapi.progress.util.ProgressWindow.stop(ProgressWindow.java:285)
	at org.jetbrains.research.testspark.display.custom.IJProgressIndicator.stop(IJProgressIndicator.kt:32)
	at org.jetbrains.research.testspark.tools.ToolUtils.isProcessCanceled(ToolUtils.kt:143)
	at org.jetbrains.research.testspark.tools.ToolUtils.isProcessStopped(ToolUtils.kt:138)
	at org.jetbrains.research.testspark.tools.Pipeline$runTestGeneration$1.run(Pipeline.kt:106)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:477)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:528)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:250)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:100)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:221)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:46)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:220)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:100)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:250)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:500)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Expected behavior**
No error or warning message

### PR DESCRIPTION
**Pull request by arksap2002**
# Description of changes made
`isProcessStopped` method calls relocation due to long time methods processing

# TODOs
* [x] Publish core module of version `5.0.1`.

# Other notes
Closes #213 #314

- [x] I have checked that I am merging into correct branch

### CODE REVIEW

**Comment by arksap2002** [comment]
Similar to https://github.com/JetBrains-Research/TestSpark/pull/216

**Review by pderakhshanfar — APPROVED** [review]
For now, it is fine, but in  the future, we need to find a better way to handle cancelation instead of repeating isCanceled check after each statement

**Review by Vladislav0Art — APPROVED** [review]

**Comment by Vladislav0Art** [comment]
How do you ensure that #314 gets closed?
@arksap2002

**Comment by Vladislav0Art** [comment]
> For now, it is fine, but in the future, we need to find a better way to handle cancelation instead of repeating isCanceled check after each statement

Kotlin coroutines support some smart cancelation mechanisms; transitioning to them in the future should help with this.

**Review by Vladislav0Art — APPROVED** [review]
**Before merging the PR, please answer this [question](https://github.com/JetBrains-Research/TestSpark/pull/346#issuecomment-2383421297)**.
@arksap2002

**Comment by arksap2002** [comment]
This PR is ready to merge

**Comment by Vladislav0Art** [comment]
@arksap2002 Do not forget to publish a new **patch** version of the `core` module. You have made changes to the implementation of `FeedbackCycleWithLLM`.

**Comment by Vladislav0Art** [comment]
> @arksap2002 Do not forget to publish a new **patch** version of the `core` module. You have made changes to the implementation of `FeedbackCycleWithLLM`.

Published core module of version `5.0.1`.

**Pull request merged**
